# Generated by Django 5.1.4 on 2025-04-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniSklep', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=64)),
                ('passw', models.CharField(max_length=64)),
            ],
        ),
    ]
